resoma_chat:
    resource: "@ResomaChatBundle/Resources/config/routing.yml"
    prefix:   /

resoma_notification:
    resource: "@ResomaNotificationBundle/Resources/config/routing.yml"
    prefix:   /

resoma_publication:
    resource: "@ResomaPublicationBundle/Resources/config/routing.yml"
    prefix:   /

resoma_profil:
    resource: "@ResomaProfilBundle/Resources/config/routing.yml"
    prefix:   /

resoma_site:
    resource: "@ResomaSiteBundle/Resources/config/routing.yml"
    prefix:   /

resoma_user:
    resource: "@ResomaUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

