<?php

namespace Resoma\ProfilBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AbonnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonnementRepository extends EntityRepository
{
	public function findAbonnement($user){
    	$query = $this->getEntityManager()->createQuery('SELECT a, u FROM ResomaProfilBundle:Abonnement a JOIN a.user2 u
															WHERE a.user1 = :user ORDER BY u.lastLogin DESC');
		$query->setParameter('user', $user);
	    return $query->getResult();
    }

}
