<?php

namespace Resoma\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function findUser($nom){
		$query = $this->_em->createQuery('SELECT u FROM ResomaUserBundle:User u
															WHERE u.username LIKE :username');
		$query->setParameter('username', '%'.$nom.'%');
	    return $query->getResult();
    }
}
