<?php

namespace Resoma\PublicationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ApprobationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApprobationRepository extends EntityRepository
{
}
