<?php

namespace Resoma\PublicationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ListageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListageRepository extends EntityRepository
{
	public function findListage($liste){
    	$query = $this->getEntityManager()->createQuery('SELECT l, p FROM ResomaPublicationBundle:Listage l JOIN l.publication p
															WHERE l.liste = :liste ORDER BY p.datePubli DESC');
		$query->setParameter('liste', $liste);
	    return $query->getResult();
    }
}
